/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 1991-2007 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::dsmcCyclicBoundary

Description
    Used for applying instantaneous actions on molecules colliding with a
    cyclic boundary.

SourceFiles
    dsmcCyclicBoundary.C

\*---------------------------------------------------------------------------*/

#ifndef dsmcCyclicBoundary_H
#define dsmcCyclicBoundary_H

#include "autoPtr.H"
#include "dsmcBoundaryBase.H"
#include "dsmcParcel.H"
#include "runTimeSelectionTables.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{
/*---------------------------------------------------------------------------*\
                     Class dsmcCyclicBoundary Declaration
\*---------------------------------------------------------------------------*/

class dsmcCyclicBoundary
:
    public dsmcBoundaryBase
{
protected:

    // Protected data

        //- Cyclic neighbour patch name
        word neighbPatchName_;

        //- Cyclic neighbour patch ID
        label neighbPatchId_;

        //- Faces on the dsmcCyclicBoundary
        labelList faces_;

        labelList coupledFacesA_;
        labelList coupledFacesB_;

        labelList cellsA_;
        labelList cellsB_;


    // Private Member Functions

        void getCoupledFaces(const polyMesh& mesh);


public:

    //- Runtime type information
    TypeName("dsmcCyclicBoundary");

    //- Declare runtime constructor selection table
    declareRunTimeSelectionTable
    (
        autoPtr,
        dsmcCyclicBoundary,
        dictionary,
        (
            const polyMesh& mesh,
            dsmcCloud& cloud,
            const dictionary& dict
        ),
        (mesh, cloud, dict)
    );

    //- Construct from components
    dsmcCyclicBoundary
    (
        const polyMesh& mesh,
        dsmcCloud& cloud,
        const dictionary& dict
    );


    //- Selector
    static autoPtr<dsmcCyclicBoundary> New
    (
        const polyMesh& mesh,
        dsmcCloud& cloud,
        const dictionary& dict
    );


    //- Destructor
    virtual ~dsmcCyclicBoundary() = default;


    // Member Functions

        virtual void calculateProperties() = 0;

        //- Create an initial configuration
        virtual void initialConfiguration() = 0;

        //- Control the molecule
        virtual void controlMol
        (
            dsmcParcel& mol,
            dsmcParcel::trackingData& td
        ) = 0;

        //- Output data
        virtual void output
        (
            const fileName& fixedPathName,
            const fileName& timePath
        ) = 0;


        // Access

            //- Return faces on patch
            virtual const labelList& controlPatch() const;

            //- Return the adjacent cells
            virtual const labelList& controlZone() const;

            virtual const labelList& allFaces() const;
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
