#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

cd $WM_PROJECT_USER_DIR/applications/preProcessing/solidInitialise/
wclean
wmake

cd $WM_PROJECT_USER_DIR/applications/solvers/hy2LPTFoam/BCs
wclean
wmake

cd $WM_PROJECT_USER_DIR/applications/solvers/hy2LPTFoam/
wclean
wmake

echo "-----  COMPLETE COMPILE APPLICATIONS  -----"
#------------------------------------------------------------------------------
