#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
wclean
wmake -j 4

cd $WM_PROJECT_USER_DIR/applications/solvers/casPSIFoam
wclean
wmake

cd $WM_PROJECT_USER_DIR/applications/utilities/preprocessing/solidInitialise
wclean
wmake

